/*
 * unified_afs.h:
 * This file is automatically generated; please do not edit it.
 */
/* Including ./unified_afs.p.h at beginning of unified_afs.h file. */

#ifdef AFS_NT40_ENV
#include <afs/errmap_nt.h>
#endif

#ifndef EIO
#error Cant deal with this case
#endif /* EIO */

/* Cases we know we should deal with */
#ifndef EDQUOT
#define EDQUOT ENOSPC
#endif /* EDQUOT */

/* Map everything else to EIO */
#ifndef EPERM
#define EPERM EIO
#endif /* EPERM */
#ifndef ENOENT
#define ENOENT EIO
#endif /* ENOENT */
#ifndef ESRCH
#define ESRCH EIO
#endif /* ESRCH */
#ifndef EINTR
#define EINTR EIO
#endif /* EINTR */
#ifndef ENXIO
#define ENXIO EIO
#endif /* ENXIO */
#ifndef E2BIG
#define E2BIG EIO
#endif /* E2BIG */
#ifndef ENOEXEC
#define ENOEXEC EIO
#endif /* ENOEXEC */
#ifndef EBADF
#define EBADF EIO
#endif /* EBADF */
#ifndef ECHILD
#define ECHILD EIO
#endif /* ECHILD */
#ifndef EAGAIN
#define EAGAIN EIO
#endif /* EAGAIN */
#ifndef ENOMEM
#define ENOMEM EIO
#endif /* ENOMEM */
#ifndef EACCES
#define EACCES EIO
#endif /* EACCES */
#ifndef EFAULT
#define EFAULT EIO
#endif /* EFAULT */
#ifndef ENOTBLK
#define ENOTBLK EIO
#endif /* ENOTBLK */
#ifndef EBUSY
#define EBUSY EIO
#endif /* EBUSY */
#ifndef EEXIST
#define EEXIST EIO
#endif /* EEXIST */
#ifndef EXDEV
#define EXDEV EIO
#endif /* EXDEV */
#ifndef ENODEV
#define ENODEV EIO
#endif /* ENODEV */
#ifndef ENOTDIR
#define ENOTDIR EIO
#endif /* ENOTDIR */
#ifndef EISDIR
#define EISDIR EIO
#endif /* EISDIR */
#ifndef EINVAL
#define EINVAL EIO
#endif /* EINVAL */
#ifndef ENFILE
#define ENFILE EIO
#endif /* ENFILE */
#ifndef EMFILE
#define EMFILE EIO
#endif /* EMFILE */
#ifndef ENOTTY
#define ENOTTY EIO
#endif /* ENOTTY */
#ifndef ETXTBSY
#define ETXTBSY EIO
#endif /* ETXTBSY */
#ifndef EFBIG
#define EFBIG EIO
#endif /* EFBIG */
#ifndef ENOSPC
#define ENOSPC EIO
#endif /* ENOSPC */
#ifndef ESPIPE
#define ESPIPE EIO
#endif /* ESPIPE */
#ifndef EROFS
#define EROFS EIO
#endif /* EROFS */
#ifndef EMLINK
#define EMLINK EIO
#endif /* EMLINK */
#ifndef EPIPE
#define EPIPE EIO
#endif /* EPIPE */
#ifndef EDOM
#define EDOM EIO
#endif /* EDOM */
#ifndef ERANGE
#define ERANGE EIO
#endif /* ERANGE */
#ifndef EDEADLK
#define EDEADLK EIO
#endif /* EDEADLK */
#ifndef ENAMETOOLONG
#define ENAMETOOLONG EIO
#endif /* ENAMETOOLONG */
#ifndef ENOLCK
#define ENOLCK EIO
#endif /* ENOLCK */
#ifndef ENOSYS
#define ENOSYS EIO
#endif /* ENOSYS */
#ifndef ENOTEMPTY
#define ENOTEMPTY EIO
#endif /* ENOTEMPTY */
#ifndef ELOOP
#define ELOOP EIO
#endif /* ELOOP */
#ifndef EWOULDBLOCK
#define EWOULDBLOCK EIO
#endif /* EWOULDBLOCK */
#ifndef ENOMSG
#define ENOMSG EIO
#endif /* ENOMSG */
#ifndef EIDRM
#define EIDRM EIO
#endif /* EIDRM */
#ifndef ECHRNG
#define ECHRNG EIO
#endif /* ECHRNG */
#ifndef EL2NSYNC
#define EL2NSYNC EIO
#endif /* EL2NSYNC */
#ifndef EL3HLT
#define EL3HLT EIO
#endif /* EL3HLT */
#ifndef EL3RST
#define EL3RST EIO
#endif /* EL3RST */
#ifndef ELNRNG
#define ELNRNG EIO
#endif /* ELNRNG */
#ifndef EUNATCH
#define EUNATCH EIO
#endif /* EUNATCH */
#ifndef ENOCSI
#define ENOCSI EIO
#endif /* ENOCSI */
#ifndef EL2HLT
#define EL2HLT EIO
#endif /* EL2HLT */
#ifndef EBADE
#define EBADE EIO
#endif /* EBADE */
#ifndef EBADR
#define EBADR EIO
#endif /* EBADR */
#ifndef EXFULL
#define EXFULL EIO
#endif /* EXFULL */
#ifndef ENOANO
#define ENOANO EIO
#endif /* ENOANO */
#ifndef EBADRQC
#define EBADRQC EIO
#endif /* EBADRQC */
#ifndef EBADSLT
#define EBADSLT EIO
#endif /* EBADSLT */
#ifndef EBFONT
#define EBFONT EIO
#endif /* EBFONT */
#ifndef ENOSTR
#define ENOSTR EIO
#endif /* ENOSTR */
#ifndef ENODATA
#define ENODATA EIO
#endif /* ENODATA */
#ifndef ETIME
#define ETIME EIO
#endif /* ETIME */
#ifndef ENOSR
#define ENOSR EIO
#endif /* ENOSR */
#ifndef ENONET
#define ENONET EIO
#endif /* ENONET */
#ifndef ENOPKG
#define ENOPKG EIO
#endif /* ENOPKG */
#ifndef EREMOTE
#define EREMOTE EIO
#endif /* EREMOTE */
#ifndef ENOLINK
#define ENOLINK EIO
#endif /* ENOLINK */
#ifndef EADV
#define EADV EIO
#endif /* EADV */
#ifndef ESRMNT
#define ESRMNT EIO
#endif /* ESRMNT */
#ifndef ECOMM
#define ECOMM EIO
#endif /* ECOMM */
#ifndef EPROTO
#define EPROTO EIO
#endif /* EPROTO */
#ifndef EMULTIHOP
#define EMULTIHOP EIO
#endif /* EMULTIHOP */
#ifndef EDOTDOT
#define EDOTDOT EIO
#endif /* EDOTDOT */
#ifndef EBADMSG
#define EBADMSG EIO
#endif /* EBADMSG */
#ifndef EOVERFLOW
#define EOVERFLOW EIO
#endif /* EOVERFLOW */
#ifndef ENOTUNIQ
#define ENOTUNIQ EIO
#endif /* ENOTUNIQ */
#ifndef EBADFD
#define EBADFD EIO
#endif /* EBADFD */
#ifndef EREMCHG
#define EREMCHG EIO
#endif /* EREMCHG */
#ifndef ELIBACC
#define ELIBACC EIO
#endif /* ELIBACC */
#ifndef ELIBBAD
#define ELIBBAD EIO
#endif /* ELIBBAD */
#ifndef ELIBSCN
#define ELIBSCN EIO
#endif /* ELIBSCN */
#ifndef ELIBMAX
#define ELIBMAX EIO
#endif /* ELIBMAX */
#ifndef ELIBEXEC
#define ELIBEXEC EIO
#endif /* ELIBEXEC */
#ifndef EILSEQ
#define EILSEQ EIO
#endif /* EILSEQ */
#ifndef ERESTART
#define ERESTART EIO
#endif /* ERESTART */
#ifndef ESTRPIPE
#define ESTRPIPE EIO
#endif /* ESTRPIPE */
#ifndef EUSERS
#define EUSERS EIO
#endif /* EUSERS */
#ifndef ENOTSOCK
#define ENOTSOCK EIO
#endif /* ENOTSOCK */
#ifndef EDESTADDRREQ
#define EDESTADDRREQ EIO
#endif /* EDESTADDRREQ */
#ifndef EMSGSIZE
#define EMSGSIZE EIO
#endif /* EMSGSIZE */
#ifndef EPROTOTYPE
#define EPROTOTYPE EIO
#endif /* EPROTOTYPE */
#ifndef ENOPROTOOPT
#define ENOPROTOOPT EIO
#endif /* ENOPROTOOPT */
#ifndef EPROTONOSUPPORT
#define EPROTONOSUPPORT EIO
#endif /* EPROTONOSUPPORT */
#ifndef ESOCKTNOSUPPORT
#define ESOCKTNOSUPPORT EIO
#endif /* ESOCKTNOSUPPORT */
#ifndef EOPNOTSUPP
#define EOPNOTSUPP EIO
#endif /* EOPNOTSUPP */
#ifndef EPFNOSUPPORT
#define EPFNOSUPPORT EIO
#endif /* EPFNOSUPPORT */
#ifndef EAFNOSUPPORT
#define EAFNOSUPPORT EIO
#endif /* EAFNOSUPPORT */
#ifndef EADDRINUSE
#define EADDRINUSE EIO
#endif /* EADDRINUSE */
#ifndef EADDRNOTAVAIL
#define EADDRNOTAVAIL EIO
#endif /* EADDRNOTAVAIL */
#ifndef ENETDOWN
#define ENETDOWN EIO
#endif /* ENETDOWN */
#ifndef ENETUNREACH
#define ENETUNREACH EIO
#endif /* ENETUNREACH */
#ifndef ENETRESET
#define ENETRESET EIO
#endif /* ENETRESET */
#ifndef ECONNABORTED
#define ECONNABORTED EIO
#endif /* ECONNABORTED */
#ifndef ECONNRESET
#define ECONNRESET EIO
#endif /* ECONNRESET */
#ifndef ENOBUFS
#define ENOBUFS EIO
#endif /* ENOBUFS */
#ifndef EISCONN
#define EISCONN EIO
#endif /* EISCONN */
#ifndef ENOTCONN
#define ENOTCONN EIO
#endif /* ENOTCONN */
#ifndef ESHUTDOWN
#define ESHUTDOWN EIO
#endif /* ESHUTDOWN */
#ifndef ETOOMANYREFS
#define ETOOMANYREFS EIO
#endif /* ETOOMANYREFS */
#ifndef ETIMEDOUT
#define ETIMEDOUT EIO
#endif /* ETIMEDOUT */
#ifndef ECONNREFUSED
#define ECONNREFUSED EIO
#endif /* ECONNREFUSED */
#ifndef EHOSTDOWN
#define EHOSTDOWN EIO
#endif /* EHOSTDOWN */
#ifndef EHOSTUNREACH
#define EHOSTUNREACH EIO
#endif /* EHOSTUNREACH */
#ifndef EALREADY
#define EALREADY EIO
#endif /* EALREADY */
#ifndef EINPROGRESS
#define EINPROGRESS EIO
#endif /* EINPROGRESS */
#ifndef ESTALE
#define ESTALE EIO
#endif /* ESTALE */
#ifndef EUCLEAN
#define EUCLEAN EIO
#endif /* EUCLEAN */
#ifndef ENOTNAM
#define ENOTNAM EIO
#endif /* ENOTNAM */
#ifndef ENAVAIL
#define ENAVAIL EIO
#endif /* ENAVAIL */
#ifndef EISNAM
#define EISNAM EIO
#endif /* EISNAM */
#ifndef EREMOTEIO
#define EREMOTEIO EIO
#endif /* EREMOTEIO */
#ifndef ENOMEDIUM
#define ENOMEDIUM EIO
#endif /* ENOMEDIUM */
#ifndef EMEDIUMTYPE
#define EMEDIUMTYPE EIO
#endif /* EMEDIUMTYPE */

/* End of prolog file ./unified_afs.p.h. */

#define UAEPERM                                  (49733376L)
#define UAENOENT                                 (49733377L)
#define UAESRCH                                  (49733378L)
#define UAEINTR                                  (49733379L)
#define UAEIO                                    (49733380L)
#define UAENXIO                                  (49733381L)
#define UAE2BIG                                  (49733382L)
#define UAENOEXEC                                (49733383L)
#define UAEBADF                                  (49733384L)
#define UAECHILD                                 (49733385L)
#define UAEAGAIN                                 (49733386L)
#define UAENOMEM                                 (49733387L)
#define UAEACCES                                 (49733388L)
#define UAEFAULT                                 (49733389L)
#define UAENOTBLK                                (49733390L)
#define UAEBUSY                                  (49733391L)
#define UAEEXIST                                 (49733392L)
#define UAEXDEV                                  (49733393L)
#define UAENODEV                                 (49733394L)
#define UAENOTDIR                                (49733395L)
#define UAEISDIR                                 (49733396L)
#define UAEINVAL                                 (49733397L)
#define UAENFILE                                 (49733398L)
#define UAEMFILE                                 (49733399L)
#define UAENOTTY                                 (49733400L)
#define UAETXTBSY                                (49733401L)
#define UAEFBIG                                  (49733402L)
#define UAENOSPC                                 (49733403L)
#define UAESPIPE                                 (49733404L)
#define UAEROFS                                  (49733405L)
#define UAEMLINK                                 (49733406L)
#define UAEPIPE                                  (49733407L)
#define UAEDOM                                   (49733408L)
#define UAERANGE                                 (49733409L)
#define UAEDEADLK                                (49733410L)
#define UAENAMETOOLONG                           (49733411L)
#define UAENOLCK                                 (49733412L)
#define UAENOSYS                                 (49733413L)
#define UAENOTEMPTY                              (49733414L)
#define UAELOOP                                  (49733415L)
#define UAEWOULDBLOCK                            (49733416L)
#define UAENOMSG                                 (49733417L)
#define UAEIDRM                                  (49733418L)
#define UAECHRNG                                 (49733419L)
#define UAEL2NSYNC                               (49733420L)
#define UAEL3HLT                                 (49733421L)
#define UAEL3RST                                 (49733422L)
#define UAELNRNG                                 (49733423L)
#define UAEUNATCH                                (49733424L)
#define UAENOCSI                                 (49733425L)
#define UAEL2HLT                                 (49733426L)
#define UAEBADE                                  (49733427L)
#define UAEBADR                                  (49733428L)
#define UAEXFULL                                 (49733429L)
#define UAENOANO                                 (49733430L)
#define UAEBADRQC                                (49733431L)
#define UAEBADSLT                                (49733432L)
#define UAEBFONT                                 (49733433L)
#define UAENOSTR                                 (49733434L)
#define UAENODATA                                (49733435L)
#define UAETIME                                  (49733436L)
#define UAENOSR                                  (49733437L)
#define UAENONET                                 (49733438L)
#define UAENOPKG                                 (49733439L)
#define UAEREMOTE                                (49733440L)
#define UAENOLINK                                (49733441L)
#define UAEADV                                   (49733442L)
#define UAESRMNT                                 (49733443L)
#define UAECOMM                                  (49733444L)
#define UAEPROTO                                 (49733445L)
#define UAEMULTIHOP                              (49733446L)
#define UAEDOTDOT                                (49733447L)
#define UAEBADMSG                                (49733448L)
#define UAEOVERFLOW                              (49733449L)
#define UAENOTUNIQ                               (49733450L)
#define UAEBADFD                                 (49733451L)
#define UAEREMCHG                                (49733452L)
#define UAELIBACC                                (49733453L)
#define UAELIBBAD                                (49733454L)
#define UAELIBSCN                                (49733455L)
#define UAELIBMAX                                (49733456L)
#define UAELIBEXEC                               (49733457L)
#define UAEILSEQ                                 (49733458L)
#define UAERESTART                               (49733459L)
#define UAESTRPIPE                               (49733460L)
#define UAEUSERS                                 (49733461L)
#define UAENOTSOCK                               (49733462L)
#define UAEDESTADDRREQ                           (49733463L)
#define UAEMSGSIZE                               (49733464L)
#define UAEPROTOTYPE                             (49733465L)
#define UAENOPROTOOPT                            (49733466L)
#define UAEPROTONOSUPPORT                        (49733467L)
#define UAESOCKTNOSUPPORT                        (49733468L)
#define UAEOPNOTSUPP                             (49733469L)
#define UAEPFNOSUPPORT                           (49733470L)
#define UAEAFNOSUPPORT                           (49733471L)
#define UAEADDRINUSE                             (49733472L)
#define UAEADDRNOTAVAIL                          (49733473L)
#define UAENETDOWN                               (49733474L)
#define UAENETUNREACH                            (49733475L)
#define UAENETRESET                              (49733476L)
#define UAECONNABORTED                           (49733477L)
#define UAECONNRESET                             (49733478L)
#define UAENOBUFS                                (49733479L)
#define UAEISCONN                                (49733480L)
#define UAENOTCONN                               (49733481L)
#define UAESHUTDOWN                              (49733482L)
#define UAETOOMANYREFS                           (49733483L)
#define UAETIMEDOUT                              (49733484L)
#define UAECONNREFUSED                           (49733485L)
#define UAEHOSTDOWN                              (49733486L)
#define UAEHOSTUNREACH                           (49733487L)
#define UAEALREADY                               (49733488L)
#define UAEINPROGRESS                            (49733489L)
#define UAESTALE                                 (49733490L)
#define UAEUCLEAN                                (49733491L)
#define UAENOTNAM                                (49733492L)
#define UAENAVAIL                                (49733493L)
#define UAEISNAM                                 (49733494L)
#define UAEREMOTEIO                              (49733495L)
#define UAEDQUOT                                 (49733496L)
#define UAENOMEDIUM                              (49733497L)
#define UAEMEDIUMTYPE                            (49733498L)
extern void initialize_uae_error_table(void);
#define ERROR_TABLE_BASE_uae (49733376L)

/* for compatibility with older versions... */
#define init_uae_err_tbl initialize_uae_error_table
#define uae_err_base ERROR_TABLE_BASE_uae

/* for compatibility with other users... */
#define ERROR_TABLE_BASE_uae (49733376L)
#define init_uae_err_tbl initialize_uae_error_table
#define initialize_uae_error_table initialize_uae_error_table
#define uae_err_base ERROR_TABLE_BASE_uae
